### ISSUE TITLE
Fix size class layout variations for iPad and iPhone

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#18]
As it is now, we have to choose which device we are building for in storyboard to get the right dimensions. Maybe have separate storyboards or make some sort of universal one?

**Comment by cpmpercussion** [comment]
This should be handled by size classes [1](https://www.raywenderlich.com/113768/adaptive-layout-tutorial-in-ios-9-getting-started) [2](https://medium.com/@craiggrummitt/size-classes-in-interface-builder-in-xcode-8-74f20a541195).

At the moment, the size of the ChirpView is controlled by size classes, but it's a bit wrong due to my mistakes.

**Comment by shredlocker** [comment]
Have a look at the size_classes branch. Have made some changes to the layout, I've put everything into stack views. Makes constraints a lot easier to work with. I've changed the chirp view in IB to a stack basically, adding new chirp views as subviews. No need to add contraints in code anymore. The only problem with this is that the chirp view don't have a constant size which makes the images bigger, which results in a border effect when playing back performances..

**Comment by shredlocker** [comment]
One more thing! Maybe we should normalize the touches so that performances will sound the same no matter the size of the screen?

**Comment by cpmpercussion** [comment]
This is looking good!

Ok I see the issue with the performances on bigger screen sizes.

In the dev branch, the performance and image were just stretched out to fill the bigger performance area on the iPad. This means there are some pixellated performances, but it's not a big deal.

![screenshot 2017-08-01 10 12 14](https://user-images.githubusercontent.com/261139/28803765-40051fda-76a2-11e7-8ecf-11e45879c4b6.png)

**Comment by cpmpercussion** [comment]
Note that touches are already normalised as follows:

    let x = Double(point.x) / Double(self.frame.size.width)

in `recordTouch` and `makeSound` in `ChirpView`. This means that every touch is a double between 0 and 1.

**Comment by shredlocker** [comment]
Ok, good. I don't know what happen in that screen shot. It's like that when you're making a new performance as well, until you hit the cancel button and resets, then you can use the entire screen! See if I can fix that today

**Comment by cpmpercussion** [comment]
(Without looking at the code) I think what's happening is that the constraints for the programmatically created `chirpView`s are not being set properly, so they hug the top left corner but don't stretch to the bottom right. Not sure! If you get that figured out, I think it would be good to pull this into the dev branch (do a pull request) so that I can send it to users. It definitely looks better than the existing layout.

**Comment by shredlocker** [comment]
The problem was that I set the frame sizes in viewDidLoad, at this point the views still have the same size as they do in storyboard. Moving the code from viewDidLoad to viewDidAppear fixed it.

**Comment by shredlocker** [comment]
The only problem I have now is that you can play outside of the view. I can't remember this being a problem before?

**Comment by cpmpercussion** [comment]
I think that was possible before! Christina discovered that if you tap down in the view and then swipe outside of it, the touches are still played (and saved). I'm not worried about that particular issue right now

**Comment by shredlocker** [comment]
Maybe I just didn't try to play outside the square before!

**Comment by shredlocker** [comment]
fixed in 18e0330
