### ISSUE TITLE
Getting user avatar from cloud

### ISSUE THREAD

**Issue by shredlocker** [cpmpercussion/microjam#58]
What is the recordTypeId for the users record? When I try a record type of "Users", I get an error saying I can't query system types... I just want the avatar for specific users.

**Comment by cpmpercussion** [comment]
Looks like you can't query the "Users" type, you can only find them by ID. This is OK - we should be to find the ID using the "createdBy" field of Performance records.

**Comment by shredlocker** [comment]
Ok, good.

**Comment by cpmpercussion** [comment]
I got it somewhat working. I think we need another singleton storage class for PerformerProfiles, I've started this a bit in the WorldJamsTableViewController. Basically it's a dictionary from CKRecordIDs to PerformerProfiles, so that you can ask for a profile, and if it's not found, it is downloaded automatically.

Next step from here - add some more interesting avatars!

![screenshot 2017-08-14 16 30 48](https://user-images.githubusercontent.com/261139/29276159-fe6944ea-810d-11e7-9c20-32083c3f6406.png)

**Comment by cpmpercussion** [comment]
closed by #67
